/*
 * generated by Xtext 2.17.0
 */
package se.mdh.idt.xtext.ecore.example.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
