/*
 * generated by Xtext 2.17.0
 */
package se.mdh.idt.xtext.ecore.example.dsl.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DSLValidator extends AbstractDSLValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					DSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
